### ISSUE TITLE
独自に作成したディレクトリをコピーさせたい(configディレクトリが自動的に作成されない)

### ISSUE THREAD

**Issue by sundaycrafts** [frontainer/frontplate-cli#1]
## やりたいこと

`project_root/src/fonts` を `project_root/public/assets/fonts` にコピーしたい。
## 症状

以下のコマンドを実行しました。

``` bash
npm i frontplate-cli -g
mkdir myapp
cd myapp
frp create dev
```

この時点でREADMEの「想定される構成」にあるような、configディレクトリが生成されなかったため、設定を変更することができませんでした。
## 環境
- OS X 10.11.6(El Capitan)
- node v6.6.0 / npm 3.10.3

※nodeのバージョン管理としてnvmを使用

**Comment by frontainer** [comment]
各テンプレートに裁量を持たせるため、CLIからはconfigファイルを出力しません。

設定を変更する方法は次の２つです。
1. frp.config.jsを作成して変更したい部分を上書きする
   例: https://github.com/frontainer/wp-frontplate/blob/master/frp.config.js
2. デフォルトの設定ファイルをすべて出力する
   カスタマイズ等で初期設定を複数変更したい場合は`frp init`コマンドを実行してください。CLIのデフォルトで使われている設定ファイルが出力されるので、それをカスタマイズして使うことができます。

※ frp.config.jsがプロジェクトに存在する場合はそちらの設定で上書きされます。

なお、設定できる項目は
`https://github.com/frontainer/frontplate-cli/blob/master/frp.config.js` 及び `https://github.com/frontainer/frontplate-cli/tree/master/config` にあるjsファイルに記載されている項目です。

---

今回の場合はcopyタスクの設定なので、次のコードを`frp.config.js`としてプロジェクトルートにおいておくと動作すると思います。

``` js
'use strict';
module.exports = function(production) {
    return {
        copy: {
          "project_root/src/fonts/**/*": "project_root/public/assets/fonts"
        }
    }
};
```

**Comment by frontainer** [comment]
`src/lib/**/*` は自動的に`public/assets/lib`に複製されるので、そこに複製するファイルは集約しましょうということになったので本件は閉じます

**Comment by sundaycrafts** [comment]
ありがとうございます！
`frp init` README見逃してました…
