### ISSUE TITLE
EJSのsource pathが変更されたことによる互換性問題とその一時的対策

### ISSUE THREAD

**Issue by ktogo** [frontainer/frontplate-cli#12]
## 概要
Frontplate CLIのアップデート後、EJSのビルド先ディレクトリが書き換わってしまいました。これにより既存プロジェクトのビルド時に「出力先が変わったのでパスの参照が崩れた」といった問題が発生しております。

ソースファイルが `/src/view/index.ejs` の場合の出力先の違いの例:
- 変更**前**: `/public/index.html`
- 変更**後**: `/public/view/index.html`

## 原因
コミット 51f68e92e5397c7c7230bc1cc033e29a5effddc1 によりEJSの読み込みパスが変更されため、ビルド時に `view/` ディレクトリの構造ごと出力されるようになりました。

## 影響を受けるバージョン
[v2.0.8](https://github.com/frontainer/frontplate-cli/releases/tag/v2.0.8) 以降

## 既存プロジェクトに対する暫定的な対策
各プロジェクトの `frp.config.js` で読み込みパスを上書きすることでとりあえず元通り動くようになります。
```javascript
'use strict';
module.exports = function(production) {
    return {
		// --- ここから追加 ---
		html: {
			src: `src/view/**/*.ejs`
		}
		// --- ここまで ---
    }
};
```

**Comment by frontainer** [comment]
Wikiに記載させてもらったので、こちらのIssueはクローズします 👍 
https://github.com/frontainer/frontplate-cli/wiki/11.-Q&A
